config/routes.rb
Rails.application.routes.draw do
  get 'conf/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'start/show'
  get 'conf' =>'conf#index'
  resources :tasks
  resources :branches do
    resources :tasks
  end


  root 'start#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 6}
  validates :code, presence: true, length: {minimum: 3, maximum: 8}
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :branch
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  http_basic_authenticate_with name: "root", password: "root", except: [:index, :show]

  def new
    @branch=Branch.new
  end

  def edit
    @branch = Branch.find(params[:id])
  end

  def update
    @branch=Branch.find(params[:id])

    if @branch.update(branch_params)
      redirect_to @branch
    else
      render 'edit'
    end
  end


  def create
    # render plain: params[:branche].inspect
    @branch = Branch.new(branch_params)

    if @branch.save
      redirect_to @branch
    else
      render 'new'
    end
  end

  def show
    @branch=Branch.find(params[:id])
  end

  def index
    @branch = Branch.all
  end

  def destroy
    @branch=Branch.find(params[:id])
    @branch.destroy

    redirect_to branches_path
  end

  private
  def branch_params
    params.require(:branch).permit(:name,:code,:uid)
  end


end

app/controllers/conf_controller.rb
class ConfController < ApplicationController
  def index
  end
end

app/controllers/start_controller.rb
class StartController < ApplicationController
def show
  @cucu=1
  @cucu+=1
end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  http_basic_authenticate_with name: "root", password: "root", only: :destroy

  def create
    @branch=Branch.find(params[:branch_id])
    @task=@branch.tasks.create(task_params)
    redirect_to branch_path(@branch)
  end

  def destroy
    @branch=Branch.find(params[:branch_id])
    @task=@branch.tasks.find(params[:id])
    @task.destroy
    redirect_to branch_path(@branch)
  end

  private
  def task_params
    params.require(:task).permit(:name,:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/conf_helper.rb
module ConfHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/branches/_form.html.erb
<%= form_with model: @branch, local: true  do |form| %>
    <% if @branch.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@branch.errors.count, "ошибка!","ошибки!") %> <br>
            Не правильно заполнены поля филиала!
          </h3>
          <ul>
            <% @branch.errors.full_messages.each do |msg| %>
                <li> <%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= form.label "Имя филиала" %> <br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label "КОД (из 1С)" %> <br>
      <%= form.text_field :code %>
    </p>
    <p>
      <%= form.label "УИД (из 1С)" %><br>
      <%= form.text_field :uid %>
    </p>
    <p>
      <%= form.submit "Создать \\ Изменить" %>
      <%= link_to 'Отмена', controller: 'branches' %>
    </p>

<% end %>

app/views/branches/edit.html.erb
    <h2>Изменение филиала</h2>
    <%= render 'form' %>

app/views/branches/index.html.erb
<h1>Список филиалов</h1>
<%= link_to 'Создать филиал', new_branch_path %>
<div class='table'>
<table class='list'>
  <tr>
    <th>№</th>
    <th>Имя</th>
    <th>Код</th>
    <th>УИД</th>
  </tr>

  <% @branch.each do |branch| %>
  <tr>
    <td><%= branch.id %></td>
    <td><%= link_to branch.name , branch_path(branch) %></td>
    <td><%= branch.code %></td>
    <td><%= branch.uid %></td>
    <td><%= link_to 'Изменить', edit_branch_path(branch) %></td>
    <td><%= link_to 'Удалить', branch_path(branch), method: :delete, data: {confirm: "Удалить филиал?"} %></td>
  </tr>
  <% end %>
</table>
</div>

app/views/branches/new.html.erb
    <h2>Создание филиала</h2>
<%= render 'form' %>

app/views/branches/show.html.erb
<p>
  <strong>Филиал:</strong>
  <%= @branch.name %>
</p>
<p>
  <strong>Код:</strong>
  <%= @branch.code %>
</p>
<p>
  <strong>УИД:</strong>
  <%= @branch.uid %>
</p>
<p><%= link_to 'Изменить', edit_branch_path(@branch) %></p>
<p><%= link_to 'Список филиалов', controller: 'branches' %></p>

<hr>

<h2>Добавить задачу</h2>
<%= render 'tasks/form' %>

<h2>Список задач:</h2>
<%= render @branch.tasks %>

app/views/conf/index.html.erb
<h1>Tools</h1>
<p><%= link_to 'Список филиалов', controller: 'branches' %></p>
<p><%= link_to 'Создать филиал', new_branch_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>DashBoardRarus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div id="outer">
    <div id="header">
        <div id="menu">
            <ul id="tabs">
                <li><a href="/">Таски</a></li>
                <li><a href="/conf">Управление</a></li>
            </ul>
        </div>
    </div>
    <div id="main">
        <%= yield %>
    </div>
</div>
</body>
</html>

app/views/start/show.html.erb
<h2>Доска!</h2>
<div class='table'>
<table class='list'>
<thead>
<tr>
<th>branch</th>
<th>Exchange</th>
<th>Sverka</th>
</tr>

</thead>
<tbody>
<tr class='alt1'>
<td >MSK</td>
<td><div id="circlegreen"></div></td>
<td><div id="circlered"></div></td>
</tr>
<tr class='alt2'>
<td>VLG</td>
<td><div id="circlered"></div></td>
<td><div id="circlegreen"></div></td>
</tr>
</tbody>
</table>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@branch, @branch.tasks.build], local: true) do |form| %>
    <div><p>
      <%= form.label "Название" %> <br>
      <%= form.text_field :name %></div>
    <div>
      <%= form.label "Статус" %> <br>
      <%= form.check_box :status %>
      </p></div>
    <p><%= form.submit "Назначить" %></p>
<% end %>

app/views/tasks/_task.html.erb
<p>
  <strong>Название:</strong>
  <%= task.name %>
</p>
<p>
  <strong>Статус:</strong>
  <%= task.status %>
</p>

<p>
  <%= link_to 'Удалить', [task.branch,task],
              method: :delete,
              data: {confirm: 'Действительно удалить задачу?'} %>
</p>